spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/tacoclouddb
    username: postgres
    password: root

server:
  port: 8000

#logging:
#  level:
#    root: WARN
#  file:
#    path: /var/logs
#    file: tacocloud.log


greeting:
  welcome: You are using ${spring.application.name}.

#taco:
#  orders:
#    pageSize: 10

