#spring:
#  thymeleaf:
#    cache: false
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: tacoclouddb

#  datasource:
#    generate-unique-name: false
#    name: tacocloud
#    url: jdbc:h2:mem:tacocloud

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/tacoclouddb
    username: postgres
    password: root
#  security:
#    oauth2:
#      client:
#        registration:
#          tacocloud:
#            clientId: